<?php
namespace Phone\Controller;
class MemberInfoController extends BaseController {
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $cookie_member = $_COOKIE["member_id"];
        
        if(empty($cookie_member))
        {
            $this->redirect('Login/index','页面跳转中...');
        }
        else
        {
            $this->assign("member_id",$cookie_member);
        }
    }
    public function index(){
		$this->display();
    }
    public function save(){
        if(isset($_COOKIE['memberID'])){
            $memberID = $_COOKIE['memberID'];
            $headportrait = $_POST['headportrait'];
            $username = $_POST['username'];
            $name = $_POST['name'];
            $sex = $_POST['sex'];
            $birthday = $_POST['birthday'];
            $address = $_POST['address'];
            $member = M('member')->where("id=$memberID")->find();
            if($member!=null)
            {
                if($member['username']!=null)
                {
                    $username = $member['username'];
                }
                $result = M('member')
                    ->where("id=$memberID")
                    ->data(array('headportrait'=>$headportrait,'username'=>$username,'name'=>$name,'sex'=>$sex,'birthday'=>$birthday,'address'=>$address))
                    ->save();
                if(false !== $result || 0 !== $result)
                {
                    exit("ok");
                }
                else
                {
                    exit("error");
                }
            }
            else
            {   
                exit("member_null");
            }
        }
        else{
            exit("login_null");
        }
    }
    public function MyQrCode(){
        $memberID=$_COOKIE['memberID'];
        if($memberID!=null){
            $member=M("member")->where("id=$memberID")->find();
            $this->assign("member",$member);
            $this->assign("title","我的二维码");
            $this->display();
        }
        else
        {
            $this->redirect("Login/index");
        }
    }
}
