<?php
namespace Phone\Controller;
class MyCenterController extends BaseController {
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $cookie_member = $_COOKIE["member_id"];
        if(empty($cookie_member))
        {
          $this->redirect('Login/index','页面跳转中...');
        }
        else
        {
            $this->assign("member_id",$cookie_member);
        }
    }
    public function index(){
      	$member_id = $_COOKIE['member_id'];
      	if($member_id!=null){
        	$member = M("member")->where("id=$member_id")->find();
	        $this->assign("member",$member);

            $grade = M('distribution_rule')->where("id={$member['grade']}")->find();
            $this->assign("grade",$grade);

	        $total = M('integral_record')->where("member_id=$member_id and type=1")->sum('integral');          
            if($total==null)
            {
                $total = 0;
            }
            $this->assign("total",$total);
            $withdrawal = M('integral_record')->where("member_id=$member_id and type=0")->sum('integral');
            if($withdrawal==null)
            {
                $withdrawal = 0;
            }
            $this->assign("withdrawal",$withdrawal);
	        $this->display();
      	}
      	else{
        	$this->redirect("/login");
      	}
    }
    public function dianpu(){
        $member_id = $_COOKIE['member_id'];
        $is_have = M('dianpu')->where("member_id=$member_id")->count();
        $this->assign("is_have",$is_have);
        $this->display("MyCenter/shengji");
        // if(empty($is_have))
        // {
            
        // }

    }
    public function Leaderboard(){
        $this->display();
    }
}
