<?php
namespace Phone\Controller;
class MyConsumeController extends BaseController{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $cookie_member = $_COOKIE["member_id"];
        if(empty($cookie_member))
        {
            $this->redirect('Login/index','页面跳转中...');
        }
        else
        {
            $this->assign("member_id",$cookie_member);
        }
    }
    public function index(){
        $this->display();
    }
    public function getData(){
        if(isset($_COOKIE['memberID'])){
            $id = $_GET['id'];
            $CurrentPage = $_POST['CurrentPage'];
            $time = $_POST['time'];
            $type = $_POST['type'];
            $where = "member_id=$id";
            $paginalNum = 10;
            if($CurrentPage==null||$CurrentPage<=0)
            {
                $CurrentPage = 1;
            }
            if($time!=null)
            {
                $where.=" and time like '%{$time}%'";
            }
            if($type!=null)
            {
                $where.=" and type=$type";
            }

            $new = M('consume_record')
                ->where($where)
                ->order('id desc')
                ->limit(($CurrentPage-1)*$paginalNum,$paginalNum)
                ->select();
            foreach ($new as $key => $value_new) {
                $new[$key]['title'] = msubstr($value_new['title'],0,15,'utf-8');
            }
            //print_r($new);
            if($new!=null)
            {
                $result = array("status"=>"ok","rows"=>$new);
            }
            else
            {
                $result = array("status"=>"null");
            }
        }
        else
        {
            $result = array("status"=>"no_login");
        }
        exit(json_encode($result));
    }
}