<?php
namespace Phone\Controller;
class MyRecommendController extends BaseController{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $cookie_member = $_COOKIE["member_id"];
        if(empty($cookie_member))
        {
            $this->redirect('Login/index','页面跳转中...');
        }
        else
        {
            $this->assign("member_id",$cookie_member);
        }
    }
    public function index(){
        $member_id = $_COOKIE['member_id'];
        $this->assign("member_id",$member_id);
        // print_r($member_id);
        $member = M('member')->where("id=$member_id")->find();
        if($member!=null)
        {
            $recommend = M('member')->where("inviter_id=$member_id")->select();
            foreach ($recommend as $key => $value) {
                if($value['grade']=="0")
                {
                    $recommend[$key]['grade_name'] = "游客";
                }
                if($value['grade']=="1")
                {
                    $recommend[$key]['grade_name'] = "合伙人";
                }
                if($value['grade']=="2")
                {
                    $recommend[$key]['grade_name'] = "经理";
                }
                if($value['grade']=="3")
                {
                    $recommend[$key]['grade_name'] = "总监";
                }
            }
            $this->assign("recommend",$recommend);

            // $CurrentPage = $_GET['CurrentPage'];
            // if($CurrentPage==null)
            // {
            //     $CurrentPage = 1;
            // }
            // $this->assign("CurrentPage",$CurrentPage);
        }
        $title = "我的团队";
        $this->assign("title",$title);
        $this->display();
    }
    public function getData(){
        if(isset($_COOKIE['member_id'])){
            $member_id = $_COOKIE['member_id'];
            $CurrentPage = $_POST['CurrentPage'];
            $where = "inviter=$member_id";
            $paginalNum = 10;
            if($CurrentPage==null||$CurrentPage<=0)
            {
                $CurrentPage = 1;
            }

            $new = M('member')
                ->where($where)
                ->order('id desc')
                ->limit(($CurrentPage-1)*$paginalNum,$paginalNum)
                ->select();
            //print_r($new);
            if($new!=null)
            {
                $result = array("status"=>"ok","rows"=>$new);
            }
            else
            {
                $result = array("status"=>"null");
            }
        }
        else
        {
            $result = array("status"=>"login_null");
        }
        exit(json_encode($result));
    }
    public function getChildren(){
        if(isset($_COOKIE['member_id'])){
            $id = $_GET['id'];
            $where = "inviter_id=$id";

            $recommend = M('member')
                ->where($where)
                ->order('id desc')
                ->select();
            foreach ($recommend as $key => $value) {
                if($value['grade']=="0")
                {
                    $recommend[$key]['grade_name'] = "游客";
                }
                if($value['grade']=="1")
                {
                    $recommend[$key]['grade_name'] = "合伙人";
                }
                if($value['grade']=="2")
                {
                    $recommend[$key]['grade_name'] = "经理";
                }
                if($value['grade']=="3")
                {
                    $recommend[$key]['grade_name'] = "总监";
                }
            }
            //print_r($new);
            if($recommend!=null)
            {
                $result = array("status"=>"ok","rows"=>$recommend);
            }
            else
            {
                $result = array("status"=>"null");
            }
        }
        else
        {
            $result = array("status"=>"no_login");
        }
        exit(json_encode($result));
    }
}