<?php
namespace Phone\Controller;
class MyWithdrawalController extends BaseController{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $cookie_member = $_COOKIE["member_id"];
        if(empty($cookie_member))
        {
            $this->redirect('Login/index','页面跳转中...');
        }
        else
        {
            $this->assign("member_id",$cookie_member);
        }
    }
    public function index(){
        $member_id = $_COOKIE["member_id"];
        $member = M('member')->where("id=$member_id")->find();
        $this->assign("member",$member);
        $this->display();
    }
    public function getData(){
        if(isset($_COOKIE['memberID'])){
            $memberID = $_COOKIE['memberID'];
            $CurrentPage = $_POST['CurrentPage'];
            $where = "member_id=$memberID";
            $paginalNum = 10;
            if($CurrentPage==null||$CurrentPage<=0)
            {
                $CurrentPage = 1;
            }

            $recommend = M('withdrawal_record')
                ->where($where)
                ->order('id desc')
                ->limit(($CurrentPage-1)*$paginalNum,$paginalNum)
                ->select();
            foreach ($recommend as $key => $value) {
                if($value['audit']==1)
                {
                    $recommend[$key]['audit'] = "已打款";
                }
                else
                {
                    $recommend[$key]['audit'] = "未打款";
                }
            }
            if($recommend!=null)
            {
                $result = array("status"=>"ok","rows"=>$recommend);
            }
            else
            {
                $result = array("status"=>"null");
            }
        }
        else
        {
            $result = array("status"=>"login_null");
        }
        exit(json_encode($result));
    }
    public function add(){
        if(isset($_COOKIE['memberID'])){
            $memberID = $_COOKIE['memberID'];
            $money = $_POST['money'];
            if(floor($money)!=$money)
            {
                exit("data_error");
            }
            $commission = M('member')->where("id=$memberID")->getField("commission");
            if($commission<$money)
            {
                exit("not_enough");
            }
            $withdrawal = M();
            $withdrawal->startTrans();
            //修改会员佣金
            $reduce_member_commission = M('member')->where("id=$memberID")->setDec('commission', $money);
            //添加提现记录
            $add_withdrawal_record = M('withdrawal_record')->data(array('money'=>$money,"member_id"=>$memberID))->add();
            //佣金减少记录
            $add_commission_record=M("commission_record")->data(array('commission'=>$money,"member_id"=>$memberID,"source"=>"提现","description"=>"提现{$money}元","type"=>"支出"))->add();
            if($reduce_member_commission>0&&$add_withdrawal_record>0&&$add_commission_record>0)
            {
                $withdrawal->commit();
                exit("ok");
            }
            else
            {
                $withdrawal->rollback();
                exit("error");
            }
        }
        else
        {
            exit("login_null");
        }
    }
}