<?php
namespace Phone\Controller;
class ShoppingCartController extends BaseController {
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $cookie_member = $_COOKIE["member_id"];
        if(empty($cookie_member))
        {
            $this->redirect('Login/index','页面跳转中...');
        }
        else
        {
            $this->assign("member_id",$cookie_member);
        }
    }
    public function index(){
        $member_id = $_COOKIE['member_id'];
        if(empty($member_id)){
            $member_id = 0;
            $member_type = 0;
        }
        else
        {
            $member = M('member')->where("id=$member_id")->find();
            $member_type = $member['type'];
        }
        $this->assign("member_id",$member_id);
        $this->assign("member_type",$member_type);
        $this->display();
    }
}