<?php
namespace Phone\Controller;
class SignController extends BaseController{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $cookie_member = $_COOKIE["member_id"];
        if(empty($cookie_member))
        {
            $this->redirect('Login/index','页面跳转中...');
        }
        else
        {
            $this->assign("member_id",$cookie_member);
        }
    }
    public function index(){
			
		$this->sign_in();
        $this->display();
    }
	
	//签到
	public function sign_in(){
			$get_coupon = 1; //签到1天赠送优惠券
	        $get_added_integral = 5; //连续签到N天额外赠送优惠券
	        $continuous_day = 10; //连续签到多少天可领额优惠券
	        
	        //**************************************************************
	        $start_time = strtotime(date('Y-m-d'));//今天凌晨的时间戳
	        $year = date("Y"); //今天-年
	        $month = date("m"); //今天-月
	        $day = date("d"); //今天-日
	        
	        //**************************************************************
	        $yesterday = strtotime('-1 day'); //昨天的时间戳基数       
	        $yesterday_year = date('Y',$yesterday); //昨天-年
	        $yesterday_month = date('m',$yesterday); //昨天-月
	        $yesterday_day = date('d',$yesterday); //昨天-日
	        
	        //**************************************************************
	        //先验证今天有没有签到过
	        $Model = M('sign');
	        $record_count = $Model -> where(array('member_id'=>$_COOKIE["member_id"],'sign_time'=>array('EGT',$start_time))) -> count();
	        if($record_count){
				$a =  "今天已经签到";
//	        	$json=array(status=>"ok",msg=>"今天已经签到");
//				exit(json_encode($json));
				$this->assign('a',$a);
	        }else{
	        	$data = array(
	            'member_id' => $_COOKIE["member_id"],
	            'sign_year' => $year, //年
	            'sign_month' => $month,//月
	            'sign_day' => $day,//日
	            'get_coupon' => $get_coupon, //默认签到获得优惠券
	            'sign_time' => time(),
	       	 	);
				$Model->add($data);
				$b =  "签到成功";
				$this->assign('b',$b);
//				$json=array(status=>"ok",msg=>"签到成功");
//				exit(json_encode($json));
	        }
			
			//**************************************************************
	        //签到天数映射
			$asign_count = $Model->where(['member_id'=>$_COOKIE["member_id"]])->order('sign_time desc')->limit(1)->find();
			$arr =str_split(sprintf("%03d",$asign_count['sign_count']),1);
			$this->assign('sign_count3',$arr[0]);
			$this->assign('sign_count2',$arr[1]);
			$this->assign('sign_count1',$arr[2]);
			$this->assign('sign_count',$asign_count['sign_count']);
			
			//**************************************************************
	        //查询昨天的签到纪录
	        $where = array(
	            'member_id' => $_COOKIE["member_id"],
	            'sign_year' => $yesterday_year,
	            'sign_month' => $yesterday_month,
	            'sign_day' => $yesterday_day,
	        );
	        $yesterday_record = $Model -> where($where) -> find();
	        //有，设置连续签到天数加1,继续判断连续签到有没有达标
	        if($yesterday_record){
	            //设置连续签到天数加1
	            $sign_count = $yesterday_record['sign_count'] +1;
				$db = $Model->where(['member_id'=>$_COOKIE["member_id"]])->order('sign_time desc')->limit(1)->save(['sign_count'=>$sign_count]);
	    		
			}
			//**************************************************************
	        //判断是否领取过优惠券
			$coupon_sign = M("coupon")->order('creat_time desc')->find();
			if($coupon_sign == null){
				$this->assign('first',1);
			}else{
				$this->assign('first',$coupon_sign['coupon_sign']);
			}
			

   	}
		//优惠券
		public function coupon(){
			if(!empty($_POST)){
				$data = $_POST;
				$data['member_id'] = $_COOKIE["member_id"];
				$db = M('coupon')->add($data);
				if($db){
					$json=array(status=>"ok",msg=>"领取成功");
					exit(json_encode($json));
				}else{
					$json=array(status=>"no",msg=>"领取失败");
					exit(json_encode($json));
				}
			}
				
			
				
				
				
				
				
				
			
		}
    
}