<?php
namespace APP\Controller;
class AddressController extends BaseController {
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $cookie_member = $_COOKIE["member_id"];
        if(empty($cookie_member))
        {
            $result = array("code"=>"404","msg"=>"您尚未登陆或登陆已过期");
            exit(json_encode($result,JSON_UNESCAPED_UNICODE));
        }
    }
    /**
    * @api {GET} Address/getData  地址列表
    * @apiGroup 收货地址
    * @apiDescription 地址列表
    * @apiParam {int} member_id 会员标识
    * @apiParam {int} CurrentPage 当前页
    * @apiParam {int} paginalNum 一页显示数量
    * @apiSuccess (成功) {int} code 状态码
    * @apiSuccess (成功) {String} msg 说明
    * @apiSuccess (成功) {object} data 信息
    * @apiSuccess (成功) {int} data.id 地址标识
    * @apiSuccess (成功) {string} data.name 收件人
    * @apiSuccess (成功) {string} data.phone 联系电话
    * @apiSuccess (成功) {string} data.province 省
    * @apiSuccess (成功) {string} data.city 市
    * @apiSuccess (成功) {string} data.district 区
    * @apiSuccess (成功) {string} data.address 详细地址
    * @apiSuccess (成功) {string} data.is_default 是否默认地址。0(否)/1(是)
    * @apiSuccessExample {json} 成功返回
    *   {
    *       "code": 200,
    *       "msg": "xxx",
    *       "data": [{
    *           "id":"15",
    *           "name":"嫦娥",
    *           "phone":"13888888888",
    *           "province":"银河系",
    *           "city":"太阳系",
    *           "district":"月球",
    *           "address":"广寒宫",
    *           "is_default":"1"
    *       }]
    *   }
    */
    public function getData(){
        $member_id = $_GET['member_id'];
        $CurrentPage = $_GET['CurrentPage'];
        $paginalNum = $_GET['paginalNum'];
        if(empty($CurrentPage))
        {
            $CurrentPage = 1;
        }
        if(empty($paginalNum))
        {
            $paginalNum = 5;
        }
        
        $address = M('shopping_address')
            ->where("member_id=$member_id")
            ->order('is_default desc')
            ->limit(($CurrentPage-1)*$paginalNum,$paginalNum)
            ->select();
        if(empty($address))
        {
            $address = array();
        }
        
        $result = array("code"=>"200","msg"=>"获取成功","data"=>$address);
        exit(json_encode($result,JSON_UNESCAPED_UNICODE));
    }
    /**
    * @api {GET} Address/show  地址详情
    * @apiGroup 收货地址
    * @apiDescription 地址详情
    * @apiParam {int} id 地址标识
    * @apiParam {int} member_id 会员标识
    * @apiSuccess (成功) {int} code 状态码
    * @apiSuccess (成功) {String} msg 信息
    * @apiSuccess (成功) {object} data 详情
    * @apiSuccess (成功) {int} data.id 地址标识
    * @apiSuccess (成功) {string} data.name 收件人
    * @apiSuccess (成功) {string} data.phone 联系电话
    * @apiSuccess (成功) {string} data.province 省
    * @apiSuccess (成功) {string} data.city 市
    * @apiSuccess (成功) {string} data.district 区
    * @apiSuccess (成功) {string} data.address 地址
    * @apiSuccess (成功) {int} data.is_default 是否默认地址。0(是)/1(否)
    * @apiSuccessExample {json} 成功返回
    *   {
    *       "code": 200,
    *       "msg": "xxx",
    *       "data": {
                "id": 5,
                "name": 嫦娥,
                "phone": 13888888888,
                "province": 天庭,
                "city": 月球,
                "district": 广寒宫,
                "address": 120号,
                "is_default": 1,
            }
    *   }
    * @apiError (失败) {int} code 状态吗
    * @apiError (失败) {String} msg 信息
    * @apiErrorExample {json} 失败返回
    *   {
    *       "code": 500
    *       "msg": "xxx"
    *   }
    */
    public function show(){
        $id = $_GET['id'];
        if($id!=null)
        {
            $member_id = $_GET['member_id'];
            $address = M('shopping_address')->where("id=$id and member_id=$member_id")->find();
            if($address!=null)
            {
                $result = array("code"=>"200","msg"=>"获取信息成功","data"=>$address);
            }
            else
            {
                $address = array();
                $result = array("code"=>"404","msg"=>"数据不存在");
            }
        }
        else
        {
            $address = array();
            $result = array("code"=>"404","msg"=>"请选择修改的地址");
        }
        $json_result = json_encode($result,JSON_UNESCAPED_UNICODE);
        exit($json_result);
    }
    /**
    * @api {POST} Address/save  修改收货地址
    * @apiGroup 收货地址
    * @apiDescription 修改收货地址
    * @apiParam {int} id 地址标识
    * @apiParam {String} name 收件人
    * @apiParam {String} phone 联系电话
    * @apiParam {String} province 省
    * @apiParam {String} city 市
    * @apiParam {String} district 区
    * @apiParam {String} address 地址
    * @apiParam {int} member_id 当前会员
    * @apiSuccess (成功) {int} code 状态码
    * @apiSuccess (成功) {String} msg 信息
    * @apiSuccessExample {json} 成功返回
    *   {
    *       "code": 200,
    *       "msg": "添加成功"
    *   }
    *
    */
    public function save(){
        $member_id = $_POST['member_id'];
        $id = $_POST['id'];
        $name = $_POST['name'];
        $phone = $_POST['phone'];
        $Phones = '/^1[3,5,7,8]\d{9}$/i';
        $province = $_POST['province'];
        $city = $_POST['city'];
        $district = $_POST['district'];
        $address = $_POST['address'];
        $is_default = $_POST['is_default'];
        $addresss = '/^.{5,100}$/i';
        if($name==null){
            $result = array("code"=>"500","msg"=>"请输入收货地址");
            exit(json_encode($result,JSON_UNESCAPED_UNICODE));
        }
        if($phone==null){
            $result = array("code"=>"500","msg"=>"请输入联系电话");
            exit(json_encode($result,JSON_UNESCAPED_UNICODE));
        }
        if(!preg_match($Phones,$phone)){
            $result = array("code"=>"500","msg"=>"请输入正确的联系电话");
            exit(json_encode($result,JSON_UNESCAPED_UNICODE));
        }
        if($province==null||$city==null||$district==null){
            $result = array("code"=>"500","msg"=>"请选择通讯区域");
            exit(json_encode($result,JSON_UNESCAPED_UNICODE));
        }
        if($address==null){
            $result = array("code"=>"500","msg"=>"请输入通讯地址");
            exit(json_encode($result,JSON_UNESCAPED_UNICODE));
        }
        if(!preg_match($addresss,$address)){
            $result = array("code"=>"500","msg"=>"请输入正确的通讯地址");
            exit(json_encode($result,JSON_UNESCAPED_UNICODE));
        }
        if(empty($is_default)){
        	$is_default = 0;
        }
        //添加地址
        if($is_default=="1")
        {
        	$edit_default = M('shopping_address')->where("member_id=$member_id")->save(array('is_default'=>"0"));
        }
        else
        {
        	$edit_default = "1";
        }
        if($id==null)
        {
        	$result = M('shopping_address')->data(array('name'=>$name,'phone'=>$phone,'province'=>$province,'city'=>$city,'district'=>$district,'address'=>$address,"member_id"=>$member_id,"is_default"=>$is_default))->add();          
        }
        //修改地址
        else
        {
            $result = M('shopping_address')->where("id=$id and member_id=$member_id")->data(array('name'=>$name,'phone'=>$phone,'province'=>$province,'city'=>$city,'district'=>$district,'address'=>$address,"is_default"=>$is_default))->save();
        }
        
        if(false !== $result || 0 !== $result || false !== $edit_default || 0 !== $edit_default)
        {
            $result = array("code"=>"200","msg"=>"保存成功");
            exit(json_encode($result,JSON_UNESCAPED_UNICODE));
        }
        else
        {
            $result = array("code"=>"500","msg"=>"保存失败");
            exit(json_encode($result,JSON_UNESCAPED_UNICODE));
        }
    }

    /**
    * @api {POST} Address/SetDefault  设置默认地址
    * @apiGroup 收货地址
    * @apiDescription 设置默认地址
    * @apiParam {int} id 地址标识
    * @apiParam {int} member_id 当前会员
    * @apiSuccess (成功) {int} code 状态码
    * @apiSuccess (成功) {String} msg 信息
    * @apiSuccessExample {json} 成功返回
    *   {
    *       "code": 200,
    *       "msg": "添加成功"
    *   }
    *   {
    *       "code": 400
    *       "msg": "添加失败"
    *   }
    *
    */
    public function SetDefault(){
        $member_id = $_POST['member_id'];
        $id = $_POST['id'];
        $IsDefault = M();
        $IsDefault->startTrans();
        $result1 = M('shopping_address')->where("member_id=$member_id")->save(array('is_default'=>"0"));
        $result2 = M("shopping_address")->where("member_id=$member_id and id=$id")->save(array('is_default'=>"1"));
        if(false !== $result1 || false !== $result2)
        {
            $IsDefault->commit();
            $result = array("code"=>"200","msg"=>"设置成功");
            exit(json_encode($result));
        }
        else
        {
            $IsDefault->rollback();
            $result = array("code"=>"400","msg"=>"设置失败");
            exit(json_encode($result,JSON_UNESCAPED_UNICODE));
        }
    } 
    /**
    * @api {POST} Address/delete  地址删除
    * @apiGroup 收货地址
    * @apiDescription 地址删除
    * @apiParam {int} id 地址标识 例1：1。  例2：1,2,3
    * @apiParam {int} member_id 当前会员
    * @apiSuccess (成功) {int} code 状态码
    * @apiSuccess (成功) {String} msg 信息
    * @apiSuccessExample {json} 成功返回
    *   {
    *       "code": 200,
    *       "msg": "添加成功"
    *   }
    *   {
    *       "code": 400
    *       "msg": "添加失败"
    *   },
    *   {
    *       "code": 404
    *       "msg": "参数错误"
    *   }
    */
    public function delete(){
        $id = $_POST['id'];
        $member_id = $_POST['member_id'];
        $address = M('shopping_address')->where("id=$id and member_id=$member_id")->find();
        if($address!=null)
        {
            $result=M('shopping_address')->where("id=$id and member_id=$member_id")->delete();
            if($address['is_default']=="1")
            {
                $setDefault = M("shopping_address")->where("member_id=$member_id")->order("id desc")->limit(1)->setInc('is_default',1); 
            }
            if($result!=null)
            {
                $result = array("code"=>"200","msg"=>"删除成功");
                exit(json_encode($result,JSON_UNESCAPED_UNICODE));
            }
            else
            {
                $result = array("code"=>"400","msg"=>"删除失败");
                exit(json_encode($result,JSON_UNESCAPED_UNICODE));
            }
        }
        else
        {
            $result = array("code"=>"404","msg"=>"地址不存在，请确认");
            exit(json_encode($result,JSON_UNESCAPED_UNICODE));
        }
    }
}
