<?php
namespace APP\Controller;
class CouponController extends BaseController{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $cookie_member = $_COOKIE["member_id"];
        if(empty($cookie_member))
        {
            $result = array("code"=>"404","msg"=>"您尚未登陆或登陆已过期");
            exit(json_encode($result,JSON_UNESCAPED_UNICODE));
        }
    }
    /**
    * @api {GET} Coupon/getData  获取优惠券
    * @apiGroup 优惠券
    * @apiDescription 提现记录
    * @apiParam {int} CurrentPage 当前页
    * @apiParam {int} paginalNum 一页显示数量
    * @apiParam {int} member_id 会员标识
	* @apiParam {int} $is_use  优惠券是否使用(0表示未使用，1表示已使用)
	* @apiParam {int} $is_time 优惠券过期判断(0表示未过期，1表示已过期)
    * @apiParam {string} time 时间。例：2019-07
    * @apiSuccess (成功) {int} code 状态码
    * @apiSuccess (成功) {String} msg 说明
    * @apiSuccess (成功) {object} data 信息
    * @apiSuccess (成功) {int} data.id 标识
    * @apiSuccess (成功) {string} data.money 金额
    * @apiSuccess (成功) {string} data.create_time 提现时间
    * @apiSuccess (成功) {string} data.audit 审核结果。0(未审核)/1(通过)/2(不通过)
    * @apiSuccessExample {json} 成功返回
    *   {
    *       "code": 200,
    *       "msg": "xxx",
    *       "data": [{
    *           "id":"15",
    *           "money":"500",
    *           "create_time":"2018-09-01",
    *           "audit":"1",
    *       }]
    *   }
    */
    public function get_data(){
        $member_id = $_COOKIE['member_id'];
        $CurrentPage = $_GET['CurrentPage'];
        $paginalNum = $_GET['paginalNum'];
        $is_use = $_GET['is_use'];			//判断是否使用
        $is_time = $_GET['is_time'];		//判断是否过期
        if($CurrentPage==null||$CurrentPage<=0)
        {
            $CurrentPage = 1;
        }
        if($CurrentPage==null||$CurrentPage<=0)
        {
            $CurrentPage = 10;
        }
        $where['member_id'] = $member_id;
		//判断是否过期
		$is_time = M('coupon')->where($where)->select();
		//当前时间
		$now_time = time();
		foreach($is_time as $k =>$v){
			//过期时间
			$past_time = $v['creat_time']+604800;
			if($past_time < $now_time){
				$past_id[] = $v['id'];
			}
		}
		
		$where['id'] = array('in',$past_id);
		$save = M('coupon')->where($where)->save(['is_time'=>'1']);
		//判断是否使用
		if($is_use == 0){
			//$is_use = 0 表示没有使用 
	        $coupon = M('coupon')
	            ->where(['member_id'=>$member_id,'is_use'=>0,'is_time'=>0])
	            ->limit(($CurrentPage-1)*$paginalNum,$paginalNum)
	            ->select();
			
	        if(empty($coupon))
	        {
	            $coupon = array();
	        }
	        $result = array("code"=>"200","msg"=>"获取未使用优惠券列表成功","data"=>$coupon);
	        exit(json_encode($result,JSON_UNESCAPED_UNICODE));
        }else if($is_use == 1){
        	//$is_use = 1 表示没有使用
        	 $coupon = M('coupon')
	            ->where(['member_id'=>$member_id,'is_use'=>1])
	            ->limit(($CurrentPage-1)*$paginalNum,$paginalNum)
	            ->select();
			
	        if(empty($coupon))
	        {
	            $coupon = array();
	        }
	        $result = array("code"=>"200","msg"=>"获取使用优惠券列表成功","data"=>$coupon);
	        exit(json_encode($result,JSON_UNESCAPED_UNICODE));
        }else if($is_use == 3){
        	//优惠券过期判断，
        	$coupon = M('coupon')
	            ->where(['member_id'=>$member_id,'is_use'=>0,'is_time'=>1])
	            ->limit(($CurrentPage-1)*$paginalNum,$paginalNum)
	            ->select();
			
	        if(empty($coupon))
	        {
	            $coupon = array();
	        }
	        $result = array("code"=>"200","msg"=>"获取过期优惠券列表成功","data"=>$coupon);
	        exit(json_encode($result,JSON_UNESCAPED_UNICODE));
        }
   
    }
    /**
    * @api {GET} Coupon/add  领取优惠券
    * @apiGroup 提现
    * @apiDescription 提现
    * @apiParam {int} money 提现金额
    * @apiParam {int} member_id 一页显示数量
    * @apiSuccess (成功) {int} code 状态码
    * @apiSuccess (成功) {String} msg 说明
    * @apiSuccessExample {json} 成功返回
    *   {
    *       "code": 200,
    *       "msg": "xxx"
    *   }
    */
    public function add(){
        if(!empty($_POST)){
				$data = $_POST;
				$data['member_id'] = $_COOKIE["member_id"];
				$data['creat_time'] = time();
				$db = M('coupon')->add($data);
				if($db){
					$json=array(status=>"ok",msg=>"领取成功");
					exit(json_encode($json));
				}else{
					$json=array(status=>"no",msg=>"领取失败");
					exit(json_encode($json));
				}
			}
    }
}