<?php
namespace APP\Controller;
class MemberInfoController extends BaseController {
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $cookie_member = $_COOKIE["member_id"];
        if(empty($cookie_member))
        {
            $result = array("code"=>"404","msg"=>"您尚未登陆或登陆已过期");
            exit(json_encode($result,JSON_UNESCAPED_UNICODE));
        }
    }
    /**
    * @api {GET} MemberInfo/get_info  获取个人信息
    * @apiGroup 个人信息
    * @apiDescription 获取个人信息
    * @apiParam {int} member_id 会员标识
    * @apiSuccess (成功) {int} code 状态码
    * @apiSuccess (成功) {string} msg 说明
    * @apiSuccess (成功) {object} data 信息
    * @apiSuccess (成功) {int} data.id 会员标识
    * @apiSuccess (成功) {string} data.nickname 昵称
    * @apiSuccess (成功) {string} data.headportrait 头像
    * @apiSuccess (成功) {string} data.name 姓名
    * @apiSuccess (成功) {string} data.phone 手机
    * @apiSuccess (成功) {string} data.sex 性别
    * @apiSuccess (成功) {string} data.birthday 生日
    * @apiSuccess (成功) {string} data.address 通讯地址
    * @apiSuccess (成功) {string} data.openid 第三方登陆标识
    * @apiSuccessExample {json} 成功返回
    *   {
    *       "code": 200,
    *       "msg": "xxx",
    *       "data": {
    *           "id":"15",
    *           "nickname":"123456",
    *           "headportrait":"15",
    *           "name":"123456",
    *           "phone":"15",
    *           "sex":"123456",
    *           "birthday":"15",
    *           "address":"123456",
    *           "openid":"15",
    *       }
    *   }
    * @apiError (失败) {int} code 状态吗
    * @apiError (失败) {String} msg 信息
    * @apiErrorExample {json} 失败返回
    *   {
    *       "code": 400
    *       "msg": "登陆失败"
    *   }
    */
    public function get_info(){
        $member_id = $_GET['member_id'];
        if(!empty($member_id))
        {
            $member = M("member")->field("id,nickname,headportrait,card_owner,card_owner,id_card,bank_card,phone")->where("id=$member_id")->find();
            if(!empty($member))
            {
                $result = array("code"=>"200","msg"=>"获取信息成功","data"=>$member);
                exit(json_encode($result));
            }
            else
            {
                $result = array("code"=>"500","msg"=>"请选择要查看的会员");
                exit(json_encode($result));
            }
        }
        else
        {
            $result = array("code"=>"404","msg"=>"请选择要查看的会员");
            exit(json_encode($result));
        }
    }
    /**
    * @api {POST} MemberInfo/save  保存用户信息
    * @apiGroup 个人信息
    * @apiDescription 保存用户信息
    * @apiParam {int} member_id 会员标识
    * @apiParam {string} nickname 昵称
    * @apiParam {string} headportrait 头像
    * @apiParam {string} name 姓名
    * @apiParam {string} phone 手机
    * @apiParam {string} sex 性别
    * @apiParam {string} birthday 生日
    * @apiParam {string} address 通讯地址
    * @apiSuccess (成功) {int} code 状态码
    * @apiSuccess (成功) {String} msg 说明
    * @apiSuccessExample {json} 成功返回
    *   {
    *       "code": 200,
    *       "msg": "xxx"
    *   }
    */

    public function save(){
        $member_id = $_POST['member_id'];
        $headportrait = $_POST['headportrait'];
        $nickname = $_POST['nickname'];
        $card_owner = $_POST['card_owner'];
        $id_card = $_POST['id_card'];
        $bank_card = $_POST['bank_card'];
        $member = M('member')->where("id=$member_id")->find();

        if($member!=null)
        {
            // if($member['nickname']!=null)
            // {
            //     $nickname = $member['nickname'];
            // }

            $result = M('member')
                ->where("id=$member_id")
                ->data(array(
                    'headportrait'=>$headportrait,
                    'nickname'=>$nickname,
                    'card_owner'=>$card_owner,
                    'id_card'=>$id_card,
                    'bank_card'=>$bank_card
                ))
                ->save();
            if(false !== $result || 0 !== $result)
            {
                $result = array("code"=>"200","msg"=>"保存成功");
                exit(json_encode($result,JSON_UNESCAPED_UNICODE));
            }
            else
            {
                $result = array("code"=>"500","msg"=>"保存失败，请重新保存");
                exit(json_encode($result,JSON_UNESCAPED_UNICODE));
            }
        }
        else
        {   
            $result = array("code"=>"404","msg"=>"会员不存在");
            exit(json_encode($result,JSON_UNESCAPED_UNICODE));
        }
    }

    /**
    * @api {GET} MemberInfo/get_qrcode  获取个人专属二维码
    * @apiGroup 个人信息
    * @apiDescription 获取个人专属二维码
    * @apiParam {int} member_id 会员标识
    * @apiSuccess (成功) {int} code 状态码
    * @apiSuccess (成功) {String} msg 说明
    * @apiSuccess (成功) {object} data 信息
    * @apiSuccess (成功) {string} data.nickname 昵称
    * @apiSuccess (成功) {string} data.headportrait 头像
    * @apiSuccess (成功) {string} data.phone 手机号
    * @apiSuccess (成功) {string} data.qrcode 二维码
    * @apiSuccessExample {json} 成功返回
    *   {
    *       "code": 200,
    *       "msg": "xxx",
    *       "data": {
    *           "nickname":"123456",
    *           "headportrait":"15",
    *           "phone":"15",
    *           "qrcode":"123456"
    *       }
    *   }
    * @apiError (失败) {int} code 状态吗
    * @apiError (失败) {String} msg 信息
    * @apiErrorExample {json} 失败返回
    *   {
    *       "code": 400,
    *       "msg": "登陆失败"
    *   }
    */
    public function get_qrcode(){
        $member_id = $_GET['member_id'];
        $member = M('member')->where("id=$member_id")->find();
        if($member['qrcode']==null)
        {
            vendor('QrCode.phpqrcode');
            $value = "http://www.xjinshangsc.com/index.php/Download?inviter=".$member_id;                  //二维码内容  
            $errorCorrectionLevel = 'L';    //容错级别   
            $matrixPointSize = 8;           //生成图片大小 
            //生成二维码图片  
            $filename = 'public/upload/qrcode/'.microtime(true).'.png';  
            //print_r($filename);
            \QRcode::png($value,$filename , $errorCorrectionLevel, $matrixPointSize, 2);
            $result = M('member')->where("id=$member_id")->setField("qrcode",$filename);
            //生成二维码成功
            if($result<=0)
            {
                $result = array("code"=>"500","msg"=>"二维码生成失败");
                exit(json_encode($result));
            }        
        }
        $member = M('member')->field('nickname,headportrait,phone,qrcode')->where("id=$member_id")->find();
        $result = array("code"=>"200","msg"=>"获取二维码成功","data"=>$member);
        exit(json_encode($result));
    }
}
