<?php
namespace APP\Controller;
class MyCommissionController extends BaseController{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $cookie_member = $_COOKIE["member_id"];
        if(empty($cookie_member))
        {
            $result = array("code"=>"404","msg"=>"您尚未登陆或登陆已过期");
            exit(json_encode($result,JSON_UNESCAPED_UNICODE));
        }
    }
    /**
    * @api {GET} MyCommission/getData  获取奖励
    * @apiGroup 我的奖励
    * @apiDescription 获取奖励
    * @apiParam {int} member_id 会员标识
    * @apiParam {int} CurrentPage 当前页
    * @apiParam {int} paginalNum 一页显示数量
    * @apiParam {string} time 时间。例：2019-07
    * @apiParam {int} type 类型。0(支出)/1(收入)
    * @apiSuccess (成功) {int} code 状态码
    * @apiSuccess (成功) {String} msg 说明
    * @apiSuccess (成功) {object} data 信息
    * @apiSuccess (成功) {int} data.totla 一共获得的奖励
    * @apiSuccess (成功) {int} data.now 现有奖励
    * @apiSuccess (成功) {int} data.rows.id 奖励标识
    * @apiSuccess (成功) {string} data.rows.commission 奖励
    * @apiSuccess (成功) {string} data.rows.create_time 时间
    * @apiSuccess (成功) {string} data.rows.source 来源
    * @apiSuccess (成功) {string} data.rows.description 描述
    * @apiSuccess (成功) {string} data.rows.type 分类0(支出)/1(收入)
    * @apiSuccessExample {json} 成功返回
    *   {
    *       "code": 200,
    *       "msg": "xxx",
    *       "data": {
                "totla":"50000",
                "now":"5000",
                "rows":[{
                    "id":"15",
        *           "commission":"200",
        *           "create_time":"2018-07-20",
        *           "source":"购物",
        *           "description":"购买xxx商品奖励",
        *           "type":"1"
                }]
    *       }
    *   }
    * @apiError (失败) {int} code 状态吗
    * @apiError (失败) {String} msg 信息
    * @apiErrorExample {json} 失败返回
    *   {
    *       "code": 400
    *       "msg": "登陆失败"
    *   }
    */
    public function getData(){
        $member_id = $_COOKIE["member_id"];
        $CurrentPage = $_GET['CurrentPage'];
        $paginalNum = $_GET['paginalNum'];
        $time = $_POST['time'];
        $type = $_POST['type'];
        $where = "member_id=$member_id";
        if($CurrentPage==null||$CurrentPage<=0)
        {
            $CurrentPage = 1;
        }
        if($paginalNum==null||$paginalNum<=0)
        {
            $paginalNum  = 8;
        }
        if($time!=null)
        {
            $where.=" and time like '%{$time}%'";
        }
        if($type!=null)
        {
            $where.=" and type=$type";
        }
        $total = M('commission_record')->where("member_id=$member_id and type=1")->sum('commission');
        if(empty($total))
        {
            $total = 0;
        }
        $now = M('member')->where("id=$member_id")->getfield("commission");
        if(empty($now))
        {
            $now = 0;
        }

        $tixian = M('withdrawal_record')->where("member_id=$member_id")->sum("money");
        if(empty($tixian))
        {
            $tixian = 0;
        }

        $new = M('commission_record')
            ->where($where)
            ->order('id desc')
            ->limit(($CurrentPage-1)*$paginalNum,$paginalNum)
            ->select();
        if(empty($new))
        {
            $new = array();
        }
        else
        {
            foreach ($new as $key => $value) {
                $new[$key]['create_time'] = date("Y-m-d H:i:s", $value['create_time']);
                if($value['type']=="1")
                {
                    $new[$key]['type'] = "+";
                }
                else
                {
                    $new[$key]['type'] = "-";
                }
            }
        }
        $data = array("total"=>$total,"now"=>$now,"tixian"=>$tixian,"rows"=>$new);
        $result = array("code"=>"200","msg"=>"获取奖励成功","data"=>$data);
        exit(json_encode($result,JSON_UNESCAPED_UNICODE));
    }
}