<?php
namespace APP\Controller;
class MyRecommendController extends BaseController{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $cookie_member = $_COOKIE["member_id"];
        if(empty($cookie_member))
        {
            $result = array("code"=>"404","msg"=>"您尚未登陆或登陆已过期");
            exit(json_encode($result,JSON_UNESCAPED_UNICODE));
        }
    }
    /**
    * @api {GET} MyRecommend/getData  推荐列表
    * @apiGroup 分销中心
    * @apiDescription 推荐列表
    * @apiParam {int} member_id 会员标识
    * @apiParam {int} CurrentPage 当前页
    * @apiParam {int} paginalNum 一页显示数量
    * @apiSuccess (成功) {int} code 状态码
    * @apiSuccess (成功) {String} msg 说明
    * @apiSuccess (成功) {object} data 信息
    * @apiSuccess (成功) {int} data.id 记录标识
    * @apiSuccess (成功) {string} data.nickname 昵称
    * @apiSuccess (成功) {string} data.phone 手机号
    * @apiSuccess (成功) {string} data.time 推荐时间
    * @apiSuccessExample {json} 成功返回
    *   {
    *       "code": 200,
    *       "msg": "xxx",
    *       "data": [{
    *           "id":"15",
    *           "nickname":"嫦娥",
    *           "phone":"13888888888",
    *           "time":"2018-06-12"
    *       }]
    *   }
    */
    public function getData(){
        $member_id = $_GET['member_id'];
        $CurrentPage = $_GET['CurrentPage'];
        $paginalNum = $_GET['paginalNum'];

        if($CurrentPage==null||$CurrentPage<=0)
        {
            $CurrentPage = 1;
        }
        if($paginalNum==null||$paginalNum<=0)
        {
            $paginalNum = 10;
        }

        $where = "inviter=$member_id";

        $recommend = M('member')
            ->where($where)
            ->order('id desc')
            ->limit(($CurrentPage-1)*$paginalNum,$paginalNum)
            ->select();
        if(empty($recommend))
        {
            $recommend = array();
        }
        $result = array("code"=>"200","msg"=>"获取成功","data"=>$recommend);
        exit(json_encode($result,JSON_UNESCAPED_UNICODE));
    }
}