<?php
namespace APP\Controller;
class MyWithdrawalController extends BaseController{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $cookie_member = $_COOKIE["member_id"];
        if(empty($cookie_member))
        {
            $result = array("code"=>"404","msg"=>"您尚未登陆或登陆已过期");
            exit(json_encode($result,JSON_UNESCAPED_UNICODE));
        }
    }
    /**
    * @api {GET} MyWithdrawal/getData  提现记录
    * @apiGroup 提现
    * @apiDescription 提现记录
    * @apiParam {int} CurrentPage 当前页
    * @apiParam {int} paginalNum 一页显示数量
    * @apiParam {int} member_id 会员标识
    * @apiParam {string} time 时间。例：2019-07
    * @apiSuccess (成功) {int} code 状态码
    * @apiSuccess (成功) {String} msg 说明
    * @apiSuccess (成功) {object} data 信息
    * @apiSuccess (成功) {int} data.id 标识
    * @apiSuccess (成功) {string} data.money 金额
    * @apiSuccess (成功) {string} data.create_time 提现时间
    * @apiSuccess (成功) {string} data.audit 审核结果。0(未审核)/1(通过)/2(不通过)
    * @apiSuccessExample {json} 成功返回
    *   {
    *       "code": 200,
    *       "msg": "xxx",
    *       "data": [{
    *           "id":"15",
    *           "money":"500",
    *           "create_time":"2018-09-01",
    *           "audit":"1",
    *       }]
    *   }
    */
    public function getData(){
        $member_id = $_COOKIE['member_id'];
        $CurrentPage = $_GET['CurrentPage'];
        $paginalNum = $_GET['paginalNum'];
        $time = $_GET['time'];
        
        if($CurrentPage==null||$CurrentPage<=0)
        {
            $CurrentPage = 1;
        }
        if($CurrentPage==null||$CurrentPage<=0)
        {
            $CurrentPage = 10;
        }
        $where = "member_id=$member_id";
        if($time!=null)
        {
            $where.=" and time like '%{$time}%'";
        }

        $record = M('withdrawal_record')
            ->where($where)
            ->order('id desc')
            ->limit(($CurrentPage-1)*$paginalNum,$paginalNum)
            ->select();

        if(empty($record))
        {
            $record = array();
        }
        $result = array("code"=>"200","msg"=>"获取记录成功","data"=>$record);
        exit(json_encode($result,JSON_UNESCAPED_UNICODE));
    }
    /**
    * @api {GET} MyWithdrawal/add  提现
    * @apiGroup 提现
    * @apiDescription 提现
    * @apiParam {int} money 提现金额
    * @apiParam {int} member_id 一页显示数量
    * @apiSuccess (成功) {int} code 状态码
    * @apiSuccess (成功) {String} msg 说明
    * @apiSuccessExample {json} 成功返回
    *   {
    *       "code": 200,
    *       "msg": "xxx"
    *   }
    */
    public function add(){
        $member_id = $_COOKIE['member_id'];
        $money = $_POST['money'];
		
        $card_owner = $_POST['card_owner'];
//		print_r($card_owner);
//		die();
        $open_bank = $_POST['open_bank'];
        $bank_card = $_POST['bank_card'];
        $phone = $_POST['phone'];
        $alipay = $_POST['alipay'];
        $pay_password = $_POST['pay_password'];
        if(floor($money)!=$money)
        {
            $result = array("code"=>"500","msg"=>"请输入正确的提现金额");
            exit(json_encode($result,JSON_UNESCAPED_UNICODE));
        }
        if(floor($money)<100)
        {
            $result = array("code"=>"500","msg"=>"您输入的提现金额不能小于100元");
            exit(json_encode($result,JSON_UNESCAPED_UNICODE));
        }
        $member = M('member')->where("id=$member_id")->find();
        // print_r($money);
        if($member['commission']<$money)
        {
            $result = array("code"=>"500","msg"=>"您的余额不足，请输入小于余额的金额");
            exit(json_encode($result,JSON_UNESCAPED_UNICODE));
        }
        if($member['withdrawal_limit']<$money)
        {
            $result = array("code"=>"500","msg"=>"您的提现额度不足，请购买礼包");
            exit(json_encode($result,JSON_UNESCAPED_UNICODE));
        }
        if(empty($card_owner)||empty($bank_card)||empty($phone)||empty($money)||empty($money))
        {
            $result = array("code"=>"500","msg"=>"请输入完整的信息后再提现");
            exit(json_encode($result,JSON_UNESCAPED_UNICODE));
        }
        $withdrawal_record = M('withdrawal_record')->where("member_id=$member_id")->find();

        $withdrawal = M();
        $withdrawal->startTrans();
        if(empty($withdrawal_record))
        {
            //如果第一次填，保存信息
            $edit_member = M('member')
                ->where("id=$member_id")
                ->data(array(
                    "card_owner"=>$card_owner,
                    'open_bank'=>$open_bank,
                    "bank_card"=>$bank_card,
                    "alipay"=>$alipay
                ))      
                ->save();
        }
        
        //修改会员佣金
        $reduce_member_commission = M('member')
            ->where("id=$member_id")
            ->data(array(
                "commission"=>$member['commission']-$money,
                "withdrawal_limit"=>$member['withdrawal_limit']-$money,
            ))
            ->save();
        //添加提现记录
        $add_withdrawal_record = M('withdrawal_record')
            ->data(array(
                'money'=>$money,
                "member_id"=>$member_id,
                'fee'=>$money*0.06,
                "card_owner"=>$card_owner,
                'open_bank'=>$open_bank,
                "bank_card"=>$bank_card,
                'phone'=>$phone,
                "alipay"=>$alipay
            ))
            ->add();
        //佣金减少记录
        $add_commission_record=M("commission_record")
            ->data(array('commission'=>$money,"member_id"=>$member_id,"create_time"=>time(),"source"=>"提现","description"=>"提现{$money}元","type"=>0))
            ->add();


        if($reduce_member_commission>0&&$add_withdrawal_record>0&&$add_commission_record>0)
        {
            $withdrawal->commit();
            $result = array("code"=>"200","msg"=>"提现成功");
            exit(json_encode($result));
        }
        else
        {
            $withdrawal->rollback();
            $result = array("code"=>"500","msg"=>"提现失败");
            exit(json_encode($result));
        }
    }

}