<?php
namespace APP\Controller;
use Think\Controller;
class WeixinPayController extends BaseController{
    //在类初始化方法中，引入相关类库    
    public function _initialize() {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $cookie_member = $_COOKIE["member_id"];
        if(empty($cookie_member))
        {
            $result = array("code"=>"404","msg"=>"您尚未登陆或登陆已过期");
            exit(json_encode($result,JSON_UNESCAPED_UNICODE));
        }
        vendor('Wxpay.Api');
        vendor('Wxpay.JsApiPay');
        vendor('Wxpay.Notify');
    }
    
    public function get_Parameters() {
        $order_id = $_GET['orderID'];
        $order = M('order_form')->where("id=$order_id")->find();
        // $openId= $_SESSION['openId'];
        if($order!=null)
        {
            $ordernum = $order['ordernum'];
            $price= $order['payment_price'];
        }
        $tools = new \JsApiPay();
        // $price=0.01*100;
        // $price=$order['payment_price'];
        $price=$price*100;//赋值给微信的
        // $ip = get_client_ip();
        $ip = get_ip();

        $input = new \WxPayUnifiedOrder();
        $input->SetBody("晋商商城");
        $input->SetAttach("购买商品");
        $input->SetOut_trade_no($ordernum);//订单号
        $input->SetTotal_fee($price);//总价
        $input->SetTime_start(date("YmdHis"));
        $input->SetTime_expire(date("YmdHis", time() + 600));
        $input->SetGoods_tag("购买商品");
        $input->SetNotify_url("http://www.xjinshangsc.com/index.php/WeixinPay/notify");
        $input->SetTrade_type("MWEB");
        $input->SetSpbill_create_ip($ip);
        // $input->SetOpenid("$openId");
        // print_r($input);
        $order = \WxPayApi::unifiedOrder($input);
        // print_r($order);
        if(!empty($order))
        {
            $mweb_url = $order['mweb_url'];
            $data = array("mweb_url"=>$mweb_url."&redirect_url=http%3a%2f%2fwww.xjinshangsc.com%2fOrder.html");
            $result = array("code"=>"200","msg"=>"获取支付参数成功","data"=>$data);
            exit(json_encode($result,JSON_UNESCAPED_UNICODE));
        }
        else
        {
            $result = array("code"=>"500","msg"=>"获取支付参数失败");
            exit(json_encode($result,JSON_UNESCAPED_UNICODE));
        }
        // exit($jsApiParameters);
        // exit(json_encode($jsApiParameters,JSON_UNESCAPED_UNICODE));
    }

    public function get_package_Parameters() {
        $order_id = $_GET['orderID'];
        $order = M('order_package')->where("id=$order_id")->find();
        // $openId= $_SESSION['openId'];
        if($order!=null)
        {
            $ordernum = $order['ordernum'];
            $price = $order['product_price'];
        }
        $tools = new \JsApiPay();
        // $price=0.01;
        // $price=$order['payment_price'];
        $price = $price*100;//赋值给微信的
        // $ip = get_client_ip();
        $ip = get_ip();

        $input = new \WxPayUnifiedOrder();
        $input->SetBody("晋商商城");
        $input->SetAttach("购买大礼包");
        $input->SetOut_trade_no($ordernum);//订单号
        $input->SetTotal_fee($price);//总价
        $input->SetTime_start(date("YmdHis"));
        $input->SetTime_expire(date("YmdHis", time() + 600));
        $input->SetGoods_tag("购买大礼包");
        $input->SetNotify_url("http://www.xjinshangsc.com/index.php/WeixinPay/package_notify_url");
        $input->SetTrade_type("MWEB");
        $input->SetSpbill_create_ip($ip);
        // $input->SetOpenid("$openId");
        // print_r($input);
        $order = \WxPayApi::unifiedOrder($input);
        // print_r($order);
        if(!empty($order))
        {
            $mweb_url = $order['mweb_url'];
            $data = array("mweb_url"=>$mweb_url."&redirect_url=http%3a%2f%2fwww.xjinshangsc.com%2fMyCenter.html");
            $result = array("code"=>"200","msg"=>"获取支付参数成功","data"=>$data);
            exit(json_encode($result,JSON_UNESCAPED_UNICODE));
        }
        else
        {
            $result = array("code"=>"500","msg"=>"获取支付参数失败");
            exit(json_encode($result,JSON_UNESCAPED_UNICODE));
        }
        // exit($jsApiParameters);
        // exit(json_encode($jsApiParameters,JSON_UNESCAPED_UNICODE));
    }

    public function get_integral_Parameters() {
        $order_id = $_GET['orderID'];
        $order = M('order_integral')->where("id=$order_id")->find();
        // $openId= $_SESSION['openId'];
        if($order!=null)
        {
            $ordernum = $order['ordernum'];
            $price = $order['money'];
        }
        $tools = new \JsApiPay();
        // $price=0.01;
        // $price=$order['payment_price'];
        $price = $price*100;//赋值给微信的
        // $ip = get_client_ip();
        $ip = get_ip();

        $input = new \WxPayUnifiedOrder();
        $input->SetBody("晋商商城");
        $input->SetAttach("积分充值");
        $input->SetOut_trade_no($ordernum);//订单号
        $input->SetTotal_fee($price);//总价
        $input->SetTime_start(date("YmdHis"));
        $input->SetTime_expire(date("YmdHis", time() + 600));
        $input->SetGoods_tag("积分充值");
        $input->SetNotify_url("http://www.xjinshangsc.com/index.php/WeixinPay/integral_notify_url");
        $input->SetTrade_type("MWEB");
        $input->SetSpbill_create_ip($ip);
        // $input->SetOpenid("$openId");
        // print_r($input);
        $order = \WxPayApi::unifiedOrder($input);
        // print_r($order);
        if(!empty($order))
        {
            $mweb_url = $order['mweb_url'];
            $data = array("mweb_url"=>$mweb_url."http%3a%2f%2fwww.xjinshangsc.com%2fMyIntegral.html");
            $result = array("code"=>"200","msg"=>"获取支付参数成功","data"=>$data);
            exit(json_encode($result,JSON_UNESCAPED_UNICODE));
        }
        else
        {
            $result = array("code"=>"500","msg"=>"获取支付参数失败");
            exit(json_encode($result,JSON_UNESCAPED_UNICODE));
        }
        // exit($jsApiParameters);
        // exit(json_encode($jsApiParameters,JSON_UNESCAPED_UNICODE));
    }
}
?>