<?php
namespace APP\Controller;
class WorkController extends BaseController{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $cookie_member = $_COOKIE["member_id"];
        if(empty($cookie_member))
        {
            $result = array("code"=>"404","msg"=>"您尚未登陆或登陆已过期");
            exit(json_encode($result,JSON_UNESCAPED_UNICODE));
        }
    }
    /**
    * @api {GET} MyWithdrawal/getData  提现记录
    * @apiGroup 提现
    * @apiDescription 提现记录
    * @apiParam {int} CurrentPage 当前页
    * @apiParam {int} paginalNum 一页显示数量
    * @apiParam {int} member_id 会员标识
    * @apiParam {string} time 时间。例：2019-07
    * @apiSuccess (成功) {int} code 状态码
    * @apiSuccess (成功) {String} msg 说明
    * @apiSuccess (成功) {object} data 信息
    * @apiSuccess (成功) {int} data.id 标识
    * @apiSuccess (成功) {string} data.money 金额
    * @apiSuccess (成功) {string} data.create_time 提现时间
    * @apiSuccess (成功) {string} data.audit 审核结果。0(未审核)/1(通过)/2(不通过)
    * @apiSuccessExample {json} 成功返回
    *   {
    *       "code": 200,
    *       "msg": "xxx",
    *       "data": [{
    *           "id":"15",
    *           "money":"500",
    *           "create_time":"2018-09-01",
    *           "audit":"1",
    *       }]
    *   }
    */
    public function get_data(){
        $member_id = $_COOKIE['member_id'];
        $CurrentPage = $_GET['CurrentPage'];
        $paginalNum = $_GET['paginalNum'];
        
        if($CurrentPage==null||$CurrentPage<=0)
        {
            $CurrentPage = 1;
        }
        if($CurrentPage==null||$CurrentPage<=0)
        {
            $CurrentPage = 10;
        }
        $where['member_id'] = $member_id;

        $work = M('work')
			->join('member on work.member_id = member.id')
            ->where($where)
            ->limit(($CurrentPage-1)*$paginalNum,$paginalNum)
            ->select();
		
        if(empty($work))
        {
            $work = array();
        }
        $result = array("code"=>"200","msg"=>"获取工作列表成功","data"=>$work);
        exit(json_encode($result,JSON_UNESCAPED_UNICODE));
    }
    /**
    * @api {GET} MyWithdrawal/add  提现
    * @apiGroup 提现
    * @apiDescription 提现
    * @apiParam {int} money 提现金额
    * @apiParam {int} member_id 一页显示数量
    * @apiSuccess (成功) {int} code 状态码
    * @apiSuccess (成功) {String} msg 说明
    * @apiSuccessExample {json} 成功返回
    *   {
    *       "code": 200,
    *       "msg": "xxx"
    *   }
    */
    public function add(){
        $member_id = $_COOKIE['member_id'];
        $picture = $_POST['picture'];
		
        $video = $_POST['video'];
        if(empty($picture))
        {
            $result = array("code"=>"500","msg"=>"请上传图片");
            exit(json_encode($result,JSON_UNESCAPED_UNICODE));
        }
        if(empty($video))
        {
            $result = array("code"=>"500","msg"=>"请上传视频");
            exit(json_encode($result,JSON_UNESCAPED_UNICODE));
        }
        $member = M('member')->where("id=$member_id")->find();
        
        //添加提现记录
        $add_work = M('work')
            ->data(array(
                "member_id"=>$member_id,
                'picture'=>$picture,
                "video"=>$video,
                
            ))
            ->add();
        if($add_work>0)
        {
            $result = array("code"=>"200","msg"=>"数据添加ok");
            exit(json_encode($result,JSON_UNESCAPED_UNICODE));
        }
        else
        {
            $result = array("code"=>"500","msg"=>"数据添加ok");
            exit(json_encode($result,JSON_UNESCAPED_UNICODE));
        }
    }
}